source 'https://github.com/diaoshihao/Specs.git'
source 'https://github.com/CocoaPods/Specs'

use_frameworks!

target 'ForeasyComponents_Example' do
  pod 'ForeasyComponents', :path => '../'

  target 'ForeasyComponents_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
